/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Luriannys Junco
 */
public class SimulationView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public SimulationView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pj1 = new javax.swing.JLabel();
        pj2 = new javax.swing.JLabel();
        habilidadesPj1 = new javax.swing.JLabel();
        habilidadesPj2 = new javax.swing.JLabel();
        puntajeSimulacion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tiempoSegundo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        swCola1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        swCola2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        swCola3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        swColaRefuerzo = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        stCola1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        stCola2 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        stCola3 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        stColaRefuerzo = new javax.swing.JList<>();
        title = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principalView.setPreferredSize(new java.awt.Dimension(1100, 800));
        principalView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("COLA DE REFUERZO");
        principalView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("COLA 1");
        principalView.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("COLA 2");
        principalView.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("COLA 3");
        principalView.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        pj1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpeg"))); // NOI18N
        pj1.setText("jLabel9");
        principalView.add(pj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 200, 480));

        pj2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpeg"))); // NOI18N
        pj2.setText("jLabel9");
        principalView.add(pj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 190, 480));

        habilidadesPj1.setForeground(java.awt.Color.white);
        habilidadesPj1.setText("jLabel9");
        principalView.add(habilidadesPj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 680, 190, 80));

        habilidadesPj2.setForeground(java.awt.Color.white);
        habilidadesPj2.setText("jLabel9");
        principalView.add(habilidadesPj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 180, 80));

        puntajeSimulacion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        puntajeSimulacion.setForeground(java.awt.Color.white);
        puntajeSimulacion.setText("0 - 0");
        principalView.add(puntajeSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Duración de un segundo");
        principalView.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, -1));

        tiempoSegundo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5", "1", "2", "3" }));
        tiempoSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoSegundoActionPerformed(evt);
            }
        });
        principalView.add(tiempoSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 735, 110, -1));

        swCola1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(swCola1);

        principalView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, 100));

        swCola2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(swCola2);

        principalView.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 200, 100));

        swCola3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(swCola3);

        principalView.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 200, 100));

        swColaRefuerzo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(swColaRefuerzo);

        principalView.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 200, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("COLA 1");
        principalView.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 160, -1, -1));

        stCola1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(stCola1);

        principalView.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 200, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("COLA 2");
        principalView.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, -1, -1));

        stCola2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(stCola2);

        principalView.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 200, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("COLA 3");
        principalView.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, -1, -1));

        stCola3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(stCola3);

        principalView.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 200, 100));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("COLA DE REFUERZO");
        principalView.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, -1, -1));

        stColaRefuerzo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(stColaRefuerzo);

        principalView.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 200, 100));

        title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        title.setForeground(java.awt.Color.white);
        title.setText("Star Wars vs Star Trek");
        principalView.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/R.jpeg"))); // NOI18N
        principalView.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        getContentPane().add(principalView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiempoSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoSegundoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel habilidadesPj1;
    private javax.swing.JLabel habilidadesPj2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel pj1;
    private javax.swing.JLabel pj2;
    private javax.swing.JPanel principalView;
    private javax.swing.JLabel puntajeSimulacion;
    private javax.swing.JList<String> stCola1;
    private javax.swing.JList<String> stCola2;
    private javax.swing.JList<String> stCola3;
    private javax.swing.JList<String> stColaRefuerzo;
    private javax.swing.JList<String> swCola1;
    private javax.swing.JList<String> swCola2;
    private javax.swing.JList<String> swCola3;
    private javax.swing.JList<String> swColaRefuerzo;
    private javax.swing.JComboBox<String> tiempoSegundo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
